# -*- coding: utf-8 -*-
"""Pwordrem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EmeBvFuUVgUCjBPe9bpO8CdFWaAHZioq
"""

İsim = "Alexander"
sonuc = input(str("İsminizi baş harfi büyük olacak şekilde giriniz "))
if sonuc == İsim :
  text= "Hello, Alexander! The password is : W@12"
else :
  text = "Hello, {} ! See you later.".format(sonuc)
print(text)